name: quran_app_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  assets_audio_player: ^3.1.1
  audio_video_progress_bar: ^2.0.1
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  http: ^1.2.0
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/svg/
